import { join } from 'path';
import { readJSON, writeMarkdown, writeJSON, fileExists } from '../utils/fs.js';
import { CONTEXT_DIR, CONTEXT_FILES } from '../constants.js';
import type { Project, Stack, Architecture, Constraints, Decisions } from '../schema/index.js';

export async function exportToMarkdown(rootDir: string): Promise<string> {
  const contextDir = join(rootDir, CONTEXT_DIR);
  
  let markdown = '# Project Context\n\n';
  markdown += '> Generated by Prelude\n\n';
  markdown += '---\n\n';
  
  // Project metadata
  const projectPath = join(contextDir, CONTEXT_FILES.PROJECT);
  if (await fileExists(projectPath)) {
    const project = await readJSON<Project>(projectPath);
    markdown += '## 📋 Project Overview\n\n';
    markdown += `**Name:** ${project.name}\n\n`;
    markdown += `**Description:** ${project.description}\n\n`;
    if (project.version) markdown += `**Version:** ${project.version}\n\n`;
    if (project.repository) markdown += `**Repository:** ${project.repository}\n\n`;
    if (project.license) markdown += `**License:** ${project.license}\n\n`;
    
    if (project.goals && project.goals.length > 0) {
      markdown += '**Goals:**\n';
      project.goals.forEach(goal => {
        markdown += `- ${goal}\n`;
      });
      markdown += '\n';
    }
    
    markdown += '---\n\n';
  }
  
  // Stack information
  const stackPath = join(contextDir, CONTEXT_FILES.STACK);
  if (await fileExists(stackPath)) {
    const stack = await readJSON<Stack>(stackPath);
    markdown += '## 🔧 Technology Stack\n\n';
    markdown += `**Language:** ${stack.language}\n\n`;
    if (stack.runtime) markdown += `**Runtime:** ${stack.runtime}\n\n`;
    if (stack.packageManager) markdown += `**Package Manager:** ${stack.packageManager}\n\n`;
    
    if (stack.frameworks && stack.frameworks.length > 0) {
      markdown += '**Frameworks:**\n';
      stack.frameworks.forEach(fw => {
        markdown += `- ${fw}\n`;
      });
      markdown += '\n';
    }
    
    if (stack.testingFrameworks && stack.testingFrameworks.length > 0) {
      markdown += '**Testing:**\n';
      stack.testingFrameworks.forEach(tf => {
        markdown += `- ${tf}\n`;
      });
      markdown += '\n';
    }
    
    if (stack.styling && stack.styling.length > 0) {
      markdown += '**Styling:**\n';
      stack.styling.forEach(s => {
        markdown += `- ${s}\n`;
      });
      markdown += '\n';
    }
    
    if (stack.database) markdown += `**Database:** ${stack.database}\n\n`;
    if (stack.orm) markdown += `**ORM:** ${stack.orm}\n\n`;
    
    markdown += '---\n\n';
  }
  
  // Architecture
  const archPath = join(contextDir, CONTEXT_FILES.ARCHITECTURE);
  if (await fileExists(archPath)) {
    const arch = await readJSON<Architecture>(archPath);
    markdown += '## 🏗️ Architecture\n\n';
    if (arch.type) markdown += `**Type:** ${arch.type}\n\n`;
    if (arch.routing) markdown += `**Routing:** ${arch.routing}\n\n`;
    if (arch.apiStyle) markdown += `**API Style:** ${arch.apiStyle}\n\n`;
    
    if (arch.patterns && arch.patterns.length > 0) {
      markdown += '**Patterns:**\n';
      arch.patterns.forEach(p => {
        markdown += `- ${p}\n`;
      });
      markdown += '\n';
    }
    
    if (arch.directories && arch.directories.length > 0) {
      markdown += '**Key Directories:**\n';
      arch.directories.slice(0, 10).forEach(dir => {
        markdown += `- \`${dir.path}\``;
        if (dir.purpose) markdown += ` - ${dir.purpose}`;
        markdown += '\n';
      });
      markdown += '\n';
    }
    
    // Source-level findings
    if ((arch as any).routes && (arch as any).routes.length > 0) {
      markdown += '**Routes:**\n';
      (arch as any).routes.forEach((r: any) => {
        const methods = r.methods ? ` [${r.methods.join(', ')}]` : '';
        const dynamic = r.isDynamic ? ' (dynamic)' : '';
        markdown += `- \`${r.path}\`${methods}${dynamic} → \`${r.file}\`\n`;
      });
      markdown += '\n';
    }

    if ((arch as any).apiEndpoints && (arch as any).apiEndpoints.length > 0) {
      markdown += '**API Endpoints:**\n';
      (arch as any).apiEndpoints.forEach((ep: any) => {
        markdown += `- \`${ep.methods.join(', ')} ${ep.path}\` → \`${ep.file}\`\n`;
      });
      markdown += '\n';
    }

    if ((arch as any).middleware && (arch as any).middleware.length > 0) {
      markdown += '**Middleware:**\n';
      (arch as any).middleware.forEach((m: any) => {
        const guards = m.guards && m.guards.length > 0 ? ` (guards: ${m.guards.join(', ')})` : '';
        markdown += `- \`${m.file}\` — ${m.type}${guards}\n`;
      });
      markdown += '\n';
    }

    if ((arch as any).reactPatterns) {
      const rp = (arch as any).reactPatterns;
      const parts: string[] = [];
      if (rp.serverComponents?.length) parts.push(`${rp.serverComponents.length} server components`);
      if (rp.clientComponents?.length) parts.push(`${rp.clientComponents.length} client components`);
      if (rp.serverActions?.length) parts.push(`${rp.serverActions.length} server action files`);
      if (rp.layouts?.length) parts.push(`${rp.layouts.length} layouts`);
      if (parts.length > 0) {
        markdown += `**React Patterns:** ${parts.join(', ')}\n`;
      }
      if (rp.hooks?.length) {
        markdown += '**Custom Hooks:**\n';
        rp.hooks.forEach((h: any) => {
          markdown += `- \`${h.file}\`: ${h.hooks.join(', ')}\n`;
        });
      }
      if (rp.providers?.length) {
        markdown += '**Providers:**\n';
        rp.providers.forEach((p: any) => {
          markdown += `- \`${p.file}\`: ${p.name}\n`;
        });
      }
      markdown += '\n';
    }

    if ((arch as any).keyFiles && (arch as any).keyFiles.length > 0) {
      markdown += '**Key Files:**\n';
      (arch as any).keyFiles.forEach((kf: any) => {
        markdown += `- \`${kf.file}\` — ${kf.role}\n`;
      });
      markdown += '\n';
    }

    markdown += '---\n\n';
  }

  // Constraints
  const constraintsPath = join(contextDir, CONTEXT_FILES.CONSTRAINTS);
  if (await fileExists(constraintsPath)) {
    const constraints = await readJSON<Constraints>(constraintsPath);
    markdown += '## ⚠️ Constraints & Preferences\n\n';
    
    if (constraints.mustUse && constraints.mustUse.length > 0) {
      markdown += '**Must Use:**\n';
      constraints.mustUse.forEach(item => {
        markdown += `- ${item}\n`;
      });
      markdown += '\n';
    }
    
    if (constraints.mustNotUse && constraints.mustNotUse.length > 0) {
      markdown += '**Must Not Use:**\n';
      constraints.mustNotUse.forEach(item => {
        markdown += `- ${item}\n`;
      });
      markdown += '\n';
    }
    
    if (constraints.codeStyle) {
      markdown += '**Code Style:**\n';
      if (constraints.codeStyle.formatter) markdown += `- Formatter: ${constraints.codeStyle.formatter}\n`;
      if (constraints.codeStyle.linter) markdown += `- Linter: ${constraints.codeStyle.linter}\n`;
      markdown += '\n';
    }
    
    if (constraints.testing) {
      markdown += '**Testing Requirements:**\n';
      markdown += `- Required: ${constraints.testing.required ? 'Yes' : 'No'}\n`;
      if (constraints.testing.strategy) markdown += `- Strategy: ${constraints.testing.strategy}\n`;
      markdown += '\n';
    }
    
    markdown += '---\n\n';
  }
  
  // Decisions
  const decisionsPath = join(contextDir, CONTEXT_FILES.DECISIONS);
  if (await fileExists(decisionsPath)) {
    const decisions = await readJSON<Decisions>(decisionsPath);
    if (decisions.decisions && decisions.decisions.length > 0) {
      markdown += '## 🧠 Key Decisions\n\n';
      
      // Show most recent 5 decisions
      const recentDecisions = decisions.decisions.slice(-5).reverse();
      recentDecisions.forEach(decision => {
        markdown += `### ${decision.title}\n\n`;
        markdown += `**Status:** ${decision.status}\n\n`;
        markdown += `**Rationale:** ${decision.rationale}\n\n`;
        
        if (decision.alternatives && decision.alternatives.length > 0) {
          markdown += '**Alternatives Considered:**\n';
          decision.alternatives.forEach(alt => {
            markdown += `- ${alt}\n`;
          });
          markdown += '\n';
        }
        
        if (decision.impact) markdown += `**Impact:** ${decision.impact}\n\n`;
        markdown += '---\n\n';
      });
    }
  }
  
  markdown += '\n*End of context export*\n';
  
  return markdown;
}

export async function exportToJSON(rootDir: string): Promise<object> {
  const contextDir = join(rootDir, CONTEXT_DIR);
  const exportData: any = {};
  
  // Read all context files
  const files = [
    { key: 'project', file: CONTEXT_FILES.PROJECT },
    { key: 'stack', file: CONTEXT_FILES.STACK },
    { key: 'architecture', file: CONTEXT_FILES.ARCHITECTURE },
    { key: 'constraints', file: CONTEXT_FILES.CONSTRAINTS },
    { key: 'decisions', file: CONTEXT_FILES.DECISIONS }
  ];
  
  for (const { key, file } of files) {
    const filePath = join(contextDir, file);
    if (await fileExists(filePath)) {
      exportData[key] = await readJSON(filePath);
    }
  }
  
  return exportData;
}

export async function exportToClaudeMd(rootDir: string): Promise<string> {
  const contextDir = join(rootDir, CONTEXT_DIR);
  let md = '# CLAUDE.md\n\n';

  // Project section
  const projectPath = join(contextDir, CONTEXT_FILES.PROJECT);
  if (await fileExists(projectPath)) {
    const project = await readJSON<Project>(projectPath);
    md += `## What is this project?\n\n`;
    md += `${project.name}`;
    if (project.description && project.description !== 'No description provided') {
      md += ` — ${project.description}`;
    }
    md += '\n\n';
    if (project.license) md += `License: ${project.license}. `;
    if ((project as any).projectVersion) md += `Version: ${(project as any).projectVersion}.`;
    if (project.license || (project as any).projectVersion) md += '\n\n';
  }

  // Commands section
  const stackPath = join(contextDir, CONTEXT_FILES.STACK);
  const archPath = join(contextDir, CONTEXT_FILES.ARCHITECTURE);
  let stack: Stack | null = null;
  let arch: Architecture | null = null;

  if (await fileExists(stackPath)) stack = await readJSON<Stack>(stackPath);
  if (await fileExists(archPath)) arch = await readJSON<Architecture>(archPath);

  if (stack) {
    md += `## Stack\n\n`;
    md += `- **Language:** ${stack.language}`;
    if (stack.runtime) md += ` (${stack.runtime})`;
    md += '\n';
    if (stack.packageManager) md += `- **Package Manager:** ${stack.packageManager}\n`;
    if (stack.frameworks && stack.frameworks.length > 0) {
      md += `- **Frameworks:** ${stack.frameworks.join(', ')}\n`;
    }
    if (stack.testingFrameworks && stack.testingFrameworks.length > 0) {
      md += `- **Testing:** ${stack.testingFrameworks.join(', ')}\n`;
    }
    if (stack.database) md += `- **Database:** ${stack.database}\n`;
    if (stack.orm) md += `- **ORM:** ${stack.orm}\n`;
    if (stack.styling && stack.styling.length > 0) {
      md += `- **Styling:** ${stack.styling.join(', ')}\n`;
    }
    if (stack.deployment) md += `- **Deployment:** ${stack.deployment}\n`;
    md += '\n';
  }

  // Architecture section
  if (arch) {
    md += `## Architecture\n\n`;
    if (arch.type) md += `**Type:** ${arch.type}\n\n`;

    if (arch.entryPoints && arch.entryPoints.length > 0) {
      md += '**Entry Points:**\n';
      arch.entryPoints.forEach(ep => {
        md += `- \`${ep.file}\` — ${ep.purpose}\n`;
      });
      md += '\n';
    }

    if (arch.directories && arch.directories.length > 0) {
      md += '**Key Directories:**\n';
      const purposeDirs = arch.directories.filter(d => d.purpose);
      const topDirs = purposeDirs.length > 0 ? purposeDirs : arch.directories.slice(0, 10);
      topDirs.forEach(dir => {
        md += `- \`${dir.path}/\``;
        if (dir.purpose) md += ` — ${dir.purpose}`;
        md += '\n';
      });
      md += '\n';
    }

    if (arch.patterns && arch.patterns.length > 0) {
      md += `**Patterns:** ${arch.patterns.join(', ')}\n\n`;
    }

    // API endpoints
    const archAny = arch as any;
    if (archAny.apiEndpoints?.length > 0) {
      md += '**API Endpoints:**\n';
      archAny.apiEndpoints.forEach((ep: any) => {
        md += `- \`${ep.methods.join(', ')} ${ep.path}\` → \`${ep.file}\`\n`;
      });
      md += '\n';
    }

    // Key files
    if (archAny.keyFiles?.length > 0) {
      md += '**Key Files:**\n';
      archAny.keyFiles.forEach((kf: any) => {
        md += `- \`${kf.file}\` — ${kf.role}\n`;
      });
      md += '\n';
    }
  }

  // Constraints section
  const constraintsPath = join(contextDir, CONTEXT_FILES.CONSTRAINTS);
  if (await fileExists(constraintsPath)) {
    const constraints = await readJSON<Constraints>(constraintsPath);
    const hasContent = (constraints.mustUse?.length ?? 0) > 0 ||
      (constraints.mustNotUse?.length ?? 0) > 0 ||
      constraints.codeStyle ||
      constraints.testing;

    if (hasContent) {
      md += `## Conventions\n\n`;

      if (constraints.mustUse && constraints.mustUse.length > 0) {
        constraints.mustUse.forEach(item => {
          md += `- ${item}\n`;
        });
      }
      if (constraints.codeStyle) {
        if (constraints.codeStyle.linter) md += `- Linter: ${constraints.codeStyle.linter}\n`;
        if (constraints.codeStyle.formatter) md += `- Formatter: ${constraints.codeStyle.formatter}\n`;
      }
      if (constraints.testing) {
        md += `- Testing: ${constraints.testing.strategy || 'required'}\n`;
      }
      if (constraints.mustNotUse && constraints.mustNotUse.length > 0) {
        md += '\n**Do NOT use:**\n';
        constraints.mustNotUse.forEach(item => {
          md += `- ${item}\n`;
        });
      }
      md += '\n';
    }
  }

  // Decisions section
  const decisionsPath = join(contextDir, CONTEXT_FILES.DECISIONS);
  if (await fileExists(decisionsPath)) {
    const decisions = await readJSON<Decisions>(decisionsPath);
    if (decisions.decisions && decisions.decisions.length > 0) {
      md += `## Key Decisions\n\n`;
      decisions.decisions.slice(-5).reverse().forEach(d => {
        md += `- **${d.title}** (${d.status}): ${d.rationale}\n`;
      });
      md += '\n';
    }
  }

  return md;
}

export async function saveExport(rootDir: string, format: 'md' | 'json' | 'claude-md' | 'cursorrules' = 'md'): Promise<string> {
  const contextDir = join(rootDir, CONTEXT_DIR);

  if (format === 'claude-md') {
    const content = await exportToClaudeMd(rootDir);
    const exportPath = join(contextDir, 'CLAUDE.md');
    await writeMarkdown(exportPath, content);
    return exportPath;
  } else if (format === 'cursorrules') {
    const content = await exportToClaudeMd(rootDir);
    const exportPath = join(contextDir, '.cursorrules');
    await writeMarkdown(exportPath, content);
    return exportPath;
  } else if (format === 'md') {
    const markdown = await exportToMarkdown(rootDir);
    const exportPath = join(contextDir, CONTEXT_FILES.EXPORT_MD);
    await writeMarkdown(exportPath, markdown);
    return exportPath;
  } else {
    const json = await exportToJSON(rootDir);
    const exportPath = join(contextDir, CONTEXT_FILES.EXPORT_JSON);
    await writeJSON(exportPath, json);
    return exportPath;
  }
}